### ISSUE TITLE
cannot call AutoCorrect in vimrc

### ISSUE THREAD

**Issue by laike9m** [panozzaj/vim-autocorrect#5]
I installed the plugin, really great tool! Calling AutoCorrect() after launching vim had no problem, but When I put `call AutoCorrect()` into .vimrc, it keeps warning me

``` bash
Error detected while processing /Users/laike9m/.vimrc:
line   52:
E117: Unknown function: AutoCorrect
Press ENTER or type command to continue
```

Here's my .vimrc file, everything is OK if I remove the last line which is `call AutoCorrect()`.

```
set nocompatible              " be iMproved
filetype off                  " required!
set nu
syntax on                     " 开启语法高亮
set fileencodings=utf-8,gbk   " 解决中文编码问题
set backspace=indent,eol,start " 保证退格键可以正常工作
set noswapfile                " 不产生swp文件
set autoread                  " 文件变化时可以实时刷新
set hlsearch                  " 高亮搜索文本
set omnifunc=syntaxcomplete#Complete " omni-complete

:set shiftwidth=4 tabstop=4
autocmd FileType html setlocal shiftwidth=2 tabstop=2
:set modifiable
:colorscheme desert

filetype plugin indent on     " required!

set rtp+=~/.vim/bundle/vundle/ " Vundle setting
call vundle#rc()
" let Vundle manage Vundle
Bundle 'gmarik/vundle'

" My bundles here:
Bundle 'scrooloose/nerdtree'
let NERDTreeShowHidden=1
let NERDTreeShowBookmarks=1                 " 显示书签
let NERDTreeIgnore=['\.\.$', '\.$', '\~$']  " 不显示.和..路径
Bundle 'jistr/vim-nerdtree-tabs'
Bundle 'klen/python-mode'
Bundle 'panozzaj/vim-autocorrect'

" set font
if has("gui_running")
    if has("gui_gtk2")
        set lines=999 columns=999     " Linux 最大化窗口
        set guifont=Inconsolata\ 12
    elseif has("gui_macvim")
        set guifont=Menlo\ Regular:h14
    elseif has("gui_win32")
        set rtp+=~/vimfiles/bundle/vundle/ " Vundle setting
        let path='~/vimfiles/bundle'
        call vundle#rc(path)
        au GUIEnter * simalt ~x       " Windows 最大化窗口
        set guifont=Consolas:h11:cANSI
    endif
endif

call AutoCorrect()
```

Thank you!

**Comment by panozzaj** [comment]
Sorry, I have not had much time to take a look at this. Is this still an issue for you?

**Comment by laike9m** [comment]
Not really. If you don't have time, that's fine.

**Comment by panozzaj** [comment]
I am not sure what version of Vundle you are using, but the [latest Vundle README](https://github.com/gmarik/Vundle.vim) says that you need to `call vundle#begin()`, declare your plugins, and then `call vundle#end()`. It seems like they are in the process of changing the Vundle interface. It seems like plugins will only be available after the `end`. Maybe Vundle has some sort of auto-end if it doesn't see one, and that is why it works when you do it after fully loading Vim, but won't work inside of the `.vimrc`.

A couple of tangential notes, as penance for taking so long with replying.. :) I don't think you need `:` at the beginning of `.vimrc` lines. You might also check the path of your Windows include at the end, based on http://stackoverflow.com/questions/20048032/configuration-doesnt-work-for-using-vundle-on-vim.

**Comment by laike9m** [comment]
I've checked I'm using the latest version of Vundle(0.10.2).   
I've modified my .vimrc adding `call vundle#begin()` and `call vundle#end()` but if I put `call AutoCorrect()` in vimrc the error still exists.

P.S. I'm using Mac so this error has nothing to do with windows path. Maybe you could reproduce it?

**Comment by panozzaj** [comment]
OK, thanks for that information. Yes, I should be able to repro locally.

**Comment by panozzaj** [comment]
I was able to reproduce the issue locally. I think the solution is one of the following:

1) `call AutoCorrect()` manually when you want to use autocorrect. This is the preferred method since it takes a couple of seconds to load the corrections, and so will slow down Vim every time you try to use it. This is my approach, and is probably why I have not run into this.
2) `source ~/.vim/bundle/vim-autocorrect/plugin/autocorrect.vim` in your ~/.vimrc above the `call AutoCorrect()`, which will execute that function and make it available.
3) Try something somewhat convoluted like http://vim.wikia.com/wiki/How_to_initialize_plugins (see augroup). Basically you need to defer calling the function until the plugin is loaded.

Hope that helps!

**Comment by daum1234** [comment]
Hi, panozzaj!

first off, thanks for you great plugin!!
and I had same issue like as laike9m ,but I got fixt with your #2 solution

**Comment by panozzaj** [comment]
FYI: I will leave this open for now until I update the documentation.

**Comment by hangjit-domain** [comment]
I tried below and it now works like a charm.

```
augroup autocorrect
    autocmd filetype * call AutoCorrect()
augroup END

```

**Comment by hrai** [comment]
I tried below and it now works like a charm.
```
augroup autocorrect
    autocmd filetype * call AutoCorrect()
augroup END
```
