### ISSUE TITLE
Regexp support

### ISSUE THREAD

**Issue by firedev** [panozzaj/vim-autocorrect#6]
Is it possible to auto correct something like

```
import Whatever form `whatever`
```

to

```
import Whatever from `whatever`
```

I keep typing `form` all the time, so some sort of regexp like this

```
:%s/\vimport\s+(\w+)\s+form/import \1 from/g
```

Would help

**Comment by panozzaj** [comment]
I don't think this is possible using Vim's `iabbrev` function, which is what vim-autocorrect uses.

I'd recommend checking out [UltiSnips](https://github.com/SirVer/ultisnips), which would allow you to define a snippet that would help you more easily import things. For example, you could say: "imp<tab>" and then it would expand that to say `import | from ""`, where `|` is where your cursor would be. You can also define this on a per-filetype basis, so you could just have this for the JS (presumably) files that you want to do this in.

Hope this helps!

**Comment by firedev** [comment]
Good point, I am not using those snippets, though, so I guess I am going to close this. Thanks.
