### ISSUE TITLE
Correcting "os" to "so" is frustrating.

### ISSUE THREAD

**Issue by haySwim** [panozzaj/vim-autocorrect#7]
https://github.com/panozzaj/vim-autocorrect/blob/938299478488bc1ea0515d7143475d6e950e5ecb/plugin/autocorrect.vim#L8194

I find that I use the word os very frequently in emails, comments, and the Go os package that this correction is mostly harmful, not helpful. I suspect that most of the people who use vim are also in tech and they might hit this same issue.

**Comment by panozzaj** [comment]
Thanks for the idea! I haven't run into this personally but I've seen a
handful of others that were similar. I would be good with a small pull
request to remove it. Then people can readd to their local configuration if
they want it.
